"""Seed reference template metadata.

No external design assets are included. Paths are placeholders only.
"""

SEED_REFERENCE_TEMPLATES = [
    {
        "template_id": "seed_cafe_strawberry_feed_001",
        "title": "딸기 디저트 감성 피드",
        "description": "핑크/크림톤의 카페 신메뉴 홍보용 정사각형 샘플",
        "category": "cafe",
        "sub_category": "dessert",
        "tags": ["딸기", "디저트", "감성", "신메뉴"],
        "business_types": ["cafe", "dessert"],
        "ad_formats": ["instagram_feed"],
        "platforms": ["instagram"],
        "aspect_ratio": "1:1",
        "width": 1080,
        "height": 1080,
        "assets": {
            "thumbnail_path": "data/reference_templates/seed_cafe_strawberry_feed_001/thumb.png",
            "preview_path": "data/reference_templates/seed_cafe_strawberry_feed_001/preview.png",
            "source_image_path": None,
        },
        "style_keywords": ["emotional", "warm", "cute"],
        "color_palette": ["#F6A5B8", "#FFF2E8", "#D85F7A"],
        "layout_hint": "top_headline_center_product_bottom_cta",
        "typography_hint": "rounded_bold_headline",
        "background_style": "soft pastel dessert mood",
        "popularity_score": 0.82,
        "license_note": "internal mock metadata only; no external design asset included",
    },
    {
        "template_id": "seed_restaurant_bbq_story_001",
        "title": "따뜻한 고기집 스토리",
        "description": "저녁 예약 유도에 맞는 세로형 음식점 샘플",
        "category": "restaurant",
        "tags": ["삼겹살", "회식", "예약", "따뜻한"],
        "business_types": ["restaurant", "bbq"],
        "ad_formats": ["instagram_story"],
        "platforms": ["instagram"],
        "aspect_ratio": "9:16",
        "width": 1080,
        "height": 1920,
        "assets": {"thumbnail_path": "data/reference_templates/seed_restaurant_bbq_story_001/thumb.png"},
        "style_keywords": ["warm", "direct", "appetizing"],
        "color_palette": ["#5C2F1B", "#F2B66D", "#FFF4E6"],
        "layout_hint": "bottom_overlay_panel",
        "typography_hint": "strong_cta",
        "background_style": "warm commercial food lighting",
        "popularity_score": 0.76,
    },
    {
        "template_id": "seed_beauty_clean_feed_001",
        "title": "클린 뷰티 프로모션",
        "category": "beauty",
        "tags": ["피부", "클린", "예약", "프로모션"],
        "business_types": ["beauty", "salon"],
        "ad_formats": ["instagram_feed"],
        "platforms": ["instagram"],
        "aspect_ratio": "1:1",
        "width": 1080,
        "height": 1080,
        "assets": {"thumbnail_path": "data/reference_templates/seed_beauty_clean_feed_001/thumb.png"},
        "style_keywords": ["clean", "premium", "minimal"],
        "color_palette": ["#F7F4EF", "#C7B8A8", "#2E2A27"],
        "layout_hint": "minimal_corner",
        "typography_hint": "thin_premium",
        "background_style": "clean cosmetic studio",
        "popularity_score": 0.71,
    },
    {
        "template_id": "seed_fitness_event_banner_001",
        "title": "피트니스 이벤트 배너",
        "category": "fitness",
        "tags": ["이벤트", "회원권", "운동", "CTA"],
        "business_types": ["fitness", "gym"],
        "ad_formats": ["banner"],
        "platforms": ["web"],
        "aspect_ratio": "16:9",
        "width": 1280,
        "height": 720,
        "assets": {"thumbnail_path": "data/reference_templates/seed_fitness_event_banner_001/thumb.png"},
        "style_keywords": ["bold", "dynamic", "event"],
        "color_palette": ["#111111", "#FFDD2D", "#F5F5F5"],
        "layout_hint": "left_text_right_product",
        "typography_hint": "heavy_sans",
        "background_style": "high contrast gym mood",
        "popularity_score": 0.68,
    },
    {
        "template_id": "seed_retail_sale_flyer_001",
        "title": "리테일 세일 전단",
        "category": "retail",
        "tags": ["세일", "매장", "가격", "행사"],
        "business_types": ["retail", "store"],
        "ad_formats": ["flyer"],
        "platforms": ["offline"],
        "aspect_ratio": "A4_vertical",
        "width": 1240,
        "height": 1754,
        "assets": {"thumbnail_path": "data/reference_templates/seed_retail_sale_flyer_001/thumb.png"},
        "style_keywords": ["event", "information", "bright"],
        "color_palette": ["#E53935", "#FFFFFF", "#FFD54F"],
        "layout_hint": "multi_zone_flyer",
        "typography_hint": "sale_badge",
        "background_style": "retail event layout",
        "popularity_score": 0.79,
    },
    {
        "template_id": "seed_event_poster_001",
        "title": "로컬 이벤트 포스터",
        "category": "event",
        "tags": ["지역", "행사", "포스터", "안내"],
        "business_types": ["event", "local"],
        "ad_formats": ["poster"],
        "platforms": ["offline"],
        "aspect_ratio": "4:5",
        "width": 1080,
        "height": 1350,
        "assets": {"thumbnail_path": "data/reference_templates/seed_event_poster_001/thumb.png"},
        "style_keywords": ["friendly", "informative", "clean"],
        "color_palette": ["#2F80ED", "#FFFFFF", "#F2C94C"],
        "layout_hint": "centered_hero",
        "typography_hint": "clear_info",
        "background_style": "simple local event poster",
        "popularity_score": 0.64,
    },
    {
        "template_id": "seed_instagram_story_flash_001",
        "title": "인스타 스토리 플래시딜",
        "category": "instagram_story",
        "tags": ["스토리", "한정", "CTA", "딜"],
        "business_types": ["retail", "cafe", "beauty"],
        "ad_formats": ["instagram_story"],
        "platforms": ["instagram"],
        "aspect_ratio": "9:16",
        "width": 1080,
        "height": 1920,
        "assets": {"thumbnail_path": "data/reference_templates/seed_instagram_story_flash_001/thumb.png"},
        "style_keywords": ["trendy", "event", "bold"],
        "color_palette": ["#7C3AED", "#FDE68A", "#FFFFFF"],
        "layout_hint": "bottom_overlay_panel",
        "typography_hint": "bold_short_headline",
        "background_style": "social flash deal mood",
        "popularity_score": 0.73,
    },
    {
        "template_id": "seed_instagram_feed_minimal_001",
        "title": "미니멀 피드 상품 소개",
        "category": "instagram_feed",
        "tags": ["미니멀", "상품", "피드", "프리미엄"],
        "business_types": ["retail", "product"],
        "ad_formats": ["instagram_feed"],
        "platforms": ["instagram"],
        "aspect_ratio": "1:1",
        "width": 1080,
        "height": 1080,
        "assets": {"thumbnail_path": "data/reference_templates/seed_instagram_feed_minimal_001/thumb.png"},
        "style_keywords": ["minimal", "premium", "clean"],
        "color_palette": ["#FAFAFA", "#111827", "#D1D5DB"],
        "layout_hint": "centered_hero",
        "typography_hint": "clean_sans",
        "background_style": "minimal product studio",
        "popularity_score": 0.86,
    },
    {
        "template_id": "seed_banner_click_cta_001",
        "title": "클릭 유도 웹 배너",
        "category": "banner",
        "tags": ["웹", "배너", "CTA", "전환"],
        "business_types": ["retail", "service"],
        "ad_formats": ["banner"],
        "platforms": ["web"],
        "aspect_ratio": "16:9",
        "width": 1280,
        "height": 720,
        "assets": {"thumbnail_path": "data/reference_templates/seed_banner_click_cta_001/thumb.png"},
        "style_keywords": ["conversion", "clean", "direct"],
        "color_palette": ["#0F172A", "#38BDF8", "#FFFFFF"],
        "layout_hint": "left_text_right_product",
        "typography_hint": "cta_button_like",
        "background_style": "clean web conversion banner",
        "popularity_score": 0.7,
    },
    {
        "template_id": "seed_flyer_info_dense_001",
        "title": "정보형 안내 플라이어",
        "category": "flyer",
        "tags": ["정보", "안내", "오프라인", "상세"],
        "business_types": ["education", "local", "service"],
        "ad_formats": ["flyer"],
        "platforms": ["offline"],
        "aspect_ratio": "A4_vertical",
        "width": 1240,
        "height": 1754,
        "assets": {"thumbnail_path": "data/reference_templates/seed_flyer_info_dense_001/thumb.png"},
        "style_keywords": ["informative", "clean", "structured"],
        "color_palette": ["#FFFFFF", "#2563EB", "#111827"],
        "layout_hint": "multi_zone_flyer",
        "typography_hint": "sectioned_info",
        "background_style": "structured information flyer",
        "popularity_score": 0.66,
    },
]

for template in SEED_REFERENCE_TEMPLATES:
    template.setdefault("source", "seed")
    template.setdefault("status", "active")
    template.setdefault("license_note", "internal mock metadata only; no external design asset included")
